### ISSUE TITLE
Typo in readme example

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/rsync-deploy#1]
The Readme has the following example

```yml
name: rsync-deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Upload Files
      uses: dataone/rsync-deploy@latest
      with:
        host: ${{ secrets.HOST }}
        group: ${{ secrets.GROUP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "/tmp/sourcedir/"
        target: "~/sometargetdir/"
```

The `uses` line should be `uses: dataoneorg/rsync-deploy@latest`. Tested on the OHI Actions. I don't have permissions to create new branches (for a develop branch); @mbjones if you give me permissions I can put the rewording in.
